spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    hikari:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mariadb://localhost:3306/stock_example
      username: root
      password: 1234
      pool-name: Spring-HikariPool

named-lock:
  datasource:
    hikari:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mariadb://localhost:3306/stock_example
      username: root
      password: 1234
      maximum-pool-size: 10
      pool-name: NamedLock-HikariPool


logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
      springframework:
        jdbc: DEBUG
